services:

  kadmin:
    profiles:
      - solo
      - main
    build:
      context: ./build
      dockerfile: Dockerfile.kadmin
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
      - keytab:/etc/krb5keytab
    hostname: kadmin
    ports:
      - "${KADMIN_PORT:-749}:749/tcp"
      - "${KADMIN_PORT:-749}:749/udp"
    environment:
      - KRB_REALM
      - REALM_NAME
      - KRB_DOMAIN_NAME
      - KRB_ADMIN_PASSWORD
      - KRB_MASTER_PASSWORD
      - KPROP_REPLICAS
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAP_REPLICAS

  kdc:
    profiles:
      - solo
      - main
      - replica
    build:
      context: ./build
      dockerfile: Dockerfile.kdc
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
    hostname: kdc
    ports:
      - "${KDC_PORT:-88}:88/tcp"
      - "${KDC_PORT:-88}:88/udp"
    environment:
      - KRB_REALM
      - KRB_DOMAIN_NAME
      - KRB_MAXWAIT
      - KPROP_REPLICAS
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAP_REPLICAS

  kprop:
    profiles:
      - main
    build:
      context: ./build
      dockerfile: Dockerfile.kprop
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
      - keytab:/etc/krb5keytab
    hostname: kprop
    environment:
      - KRB_REALM
      - KRB_DOMAIN_NAME
      - KRB_MAXWAIT
      - KPROP_CRON
      - KPROP_REPLICAS
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAP_REPLICAS
    depends_on:
      - kadmin

  kpropd:
    profiles:
      - replica
    build:
      context: ./build
      dockerfile: Dockerfile.kpropd
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
      - keytab:/etc/krb5keytab
    hostname: ${KPROPD_HOSTNAME:-kpropd}
    ports:
      - "${KPROPD_PORT:-754}:754/tcp"
    environment:
      - KRB_REALM
      - KRB_DOMAIN_NAME
      - "KPROPD_HOSTNAME=${KPROPD_HOSTNAME:-kpropd}"
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAP_SYNCREPL_PROVIDER

  slapd:
    profiles:
      - solo
      - main
      - replica
    build:
      context: ./build
      dockerfile: Dockerfile.slapd
    volumes:
      - ldap:/var/lib/openldap
      - keytab:/etc/krb5keytab
    hostname: ${LDAP_HOSTNAME:-slapd}
    ports:
      - "${LDAP_PORT:-389}:389/tcp"
    environment:
      - KRB_REALM
      - KRB_DOMAIN_NAME
      - LDAP_SUFFIX
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAP_REPLICAS
      - LDAP_SYNCREPL_PROVIDER
      - LDAP_SYNCREPL_PROVIDER_PORT
    depends_on:
      - kdc

  ldapcherry:
    profiles:
      - solo
      - main
    build:
      context: ./build
      dockerfile: Dockerfile.ldapcherry
    volumes:
      - keytab:/etc/krb5keytab
      - ./config/user_profile.mobileconfig:/etc/ldapcherry/user_profile.mobileconfig:ro
    hostname: ldapcherry
    ports:
      - "${LDAPCHERRY_PORT:-8389}:8389/tcp"
    environment:
      - KRB_REALM
      - KRB_DOMAIN_NAME
      - REALM_NAME
      - LDAP_SUFFIX
      - "LDAP_HOSTNAME=${LDAP_HOSTNAME:-slapd}"
      - LDAPCHERRY_URL
      - LDAPCHERRY_MAILFROM
      - LDAPCHERRY_PARENT_DN
      - LDAPCHERRY_ADMIN_GROUP_DN
      - LDAPCHERRY_LOGLEVEL
      - SMTP_HOST
      - SMTP_PORT
    depends_on:
      - slapd
      - kdc

  simplesamlphp:
    profiles:
      - solo
      - main
    build:
      context: ./simplesamlphp
      dockerfile: Dockerfile.php
    volumes:
      - samlcert:/var/lib/simplesamlphp/cert
    environment:
      - LDAP_SUFFIX
      - "SSP_BASE_URL=${SSP_BASE_URL:-http://localhost:8080}"
      - SSP_ADMIN_NAME
      - SSP_ADMIN_EMAIL
      - SSP_FROM_EMAIL
      - SSP_ORG_NAME
      - SSP_ORG_DISPLAY
      - SSP_ORG_URL
      - SSP_ADMIN_PASSWORD
      - SSP_SECRET_SALT
    depends_on:
      - slapd

  web:
    profiles:
      - solo
      - main
    build:
      context: ./simplesamlphp
      dockerfile: Dockerfile.nginx
    depends_on:
      - simplesamlphp
    ports:
      - "${WEB_PORT:-8080}:80"

volumes:
  kdb:
  ldap:
  keytab:
  samlcert:

