version: "3.0"

services:

  kadmin:
    build:
      context: ./build
      dockerfile: Dockerfile.kadmin
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
      - keytab:/etc/krb5keytab
    hostname: kadmin
    ports:
      - "${KADMIN_PORT:-749}:749/tcp"
      - "${KADMIN_PORT:-749}:749/udp"
    environment:
      - KRB_REALM
      - KRB_ADMIN_PASSWORD
      - KRB_MASTER_PASSWORD
      - "LDAP_FQDN=${LDAP_HOSTNAME:-slapd}.${LDAP_DOMAINNAME:-docker.lan}"

  kdc:
    build:
      context: ./build
      dockerfile: Dockerfile.kdc
    init: true
    volumes:
      - kdb:/var/lib/krb5kdc
    hostname: kdc
    ports:
      - "${KDC_PORT:-88}:88/tcp"
      - "${KDC_PORT:-88}:88/udp"
    environment:
      - KRB_REALM
    depends_on:
      - kadmin

#  kprop:
#    build:
#      context: ./build
#      dockerfile: Dockerfile.kprop
#    volumes:

  saslauthd:
    build:
      context: ./build
      dockerfile: Dockerfile.saslauthd
    init: true
    volumes:
      - keytab:/etc/krb5keytab
      - saslauthd:/var/run/saslauthd
    hostname: saslauthd
    environment:
      - KRB_REALM
    depends_on:
      - kdc

  slapd:
    build:
      context: ./build
      dockerfile: Dockerfile.slapd
    volumes:
      - ldap:/var/lib/ldap
      - keytab:/etc/krb5keytab
      - saslauthd:/var/run/saslauthd
      - slapdolc:/etc/ldap/slapd.d
    hostname: ${LDAP_HOSTNAME:-slapd}
    domainname: ${LDAP_DOMAINNAME:-docker.lan}
    ports:
      - "${LDAP_PORT:-389}:389/tcp"
    environment:
      - KRB_REALM
      - LDAP_SUFFIX
    depends_on:
      - saslauthd
      - kdc

  ldapcherry:
    build:
      context: ./build
      dockerfile: Dockerfile.ldapcherry
    volumes:
      - keytab:/etc/krb5keytab
    hostname: ldapcherry
    ports:
      - "${LDAPCHERRY_PORT:-8389}:8389/tcp"
    environment:
      - KRB_REALM
      - LDAP_SUFFIX
      - LDAPCHERRY_URL
      - LDAPCHERRY_MAILFROM
      - LDAPCHERRY_PARENT_DN
      - LDAPCHERRY_ADMIN_GROUP_DN
    depends_on:
      - slapd
      - kdc

  simplesamlphp:
    build:
      context: ./simplesamlphp
      dockerfile: Dockerfile.php
    volumes:
      - samlcert:/var/lib/simplesamlphp/cert
    environment:
      - LDAP_SUFFIX
      - "SSP_BASE_URL=${SSP_BASE_URL:-http://localhost:8080}"
      - SSP_ADMIN_NAME
      - SSP_ADMIN_EMAIL
      - SSP_FROM_EMAIL
      - SSP_ORG_NAME
      - SSP_ORG_DISPLAY
      - SSP_ORG_URL
      - SSP_ADMIN_PASSWORD
      - SSP_SECRET_SALT
    depends_on:
      - slapd

  web:
    build:
      context: ./simplesamlphp
      dockerfile: Dockerfile.nginx
    depends_on:
      - simplesamlphp
    ports:
      - "${WEB_PORT:-8080}:80"

volumes:
  kdb:
  ldap:
  slapdolc:
  keytab:
  saslauthd:
  samlcert:

